class User:
    """
    """
    def a_baumard(): return "a.baumard"
    def a_caillon(): return "a.caillon"    
    def c_durandeau(): return "c.durandeau"    
    def c_paquereau(): return "c.paquereau"
    def d_boisdron(): return "d.boisdron"
    def g_haumont(): return "g.haumont"
    def h_beaumatin(): return "h.beaumatin"
    def l_hot(): return "laura.hot"
    def n_calvez(): return "n.calvez"
    def s_bouvier(): return "stephanie.bouvier"
    def s_stephan(): return "sylvain.stephan"
    def t_des(): return "th.des"
    def v_wattier(): return "v.wattier"
